### ISSUE TITLE
Problem while running demo in linux

### ISSUE THREAD

**Issue by kshitijd20** [xavierpuigf/virtualhome#1]
Hi,
I followed the instructions in the Readme file but while running unity_demo.ipynb it shows following error when comm.reset() function is called. I am using linux executable file for unity in Ubuntu 18.04

UnityCommunicationException: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7febacf8e780>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by xavierpuigf** [comment]
Hi, this normally happens when you run haven't started the unity simulator. If you are running on Unity Desktop you should execute the .x86_64 executable and hit play. Then you should be able to run the simulator.

**Comment by kshitijd20** [comment]
![image](https://user-images.githubusercontent.com/36129805/59246326-52584400-8c1c-11e9-8197-f488b3dd4c40.png)

It doesn't have a play button. I press Ok and then the window closes and nothing happens.

**Comment by xavierpuigf** [comment]
Could you try setting the "Windowed" option and press Ok? A small window should be created with the unity logo. The window then will turn dark, meaning you can communicate with comm.reset(). I would also try reducing the graphics quality to Medium, as the window might be closing due to insufficient RAM.

**Comment by kshitijd20** [comment]
Hi Xavier, 

Thanks. I tried that but I never see the small window. I checked my Player logs and it shows the following error 

Unable to find a supported OpenGL core profile
Failed to create valid graphics context: please ensure you meet the minimum requirements
E.g. OpenGL core profile 3.2 or later for OpenGL Core renderer

I checked the output of glxinfo | grep OpenGL.  I will check after updating the OpenGL core profile although I don't know how to do that
![image](https://user-images.githubusercontent.com/36129805/59269158-a9770c80-8c4e-11e9-8904-8779bba9bf6f.png)

**Comment by xavierpuigf** [comment]
Hi, 
Indeed, it seems to be an issue with the OpenGL version. From other posts, this tends to be due to a conflict with the nvidia driver. Maybe you could try using the docker version meanwhile?

**Comment by kshitijd20** [comment]
Hi Xavier,
Thanks for the help.
I updated my nvidia driver and now it works.
