### ISSUE TITLE
How to get character camera's poses or parameters?

### ISSUE THREAD

**Issue by jaewonbae** [xavierpuigf/virtualhome#106]
Hi, thank you for providing such a great tool. 
I'm trying to extract the camera poses for each frame. But cam_data() fucntion is only supports static cameras, not character cameras. 
Is there a solution to get the parameters of the character camera or extract the camera pose for every frame? 
Thanks!

**Comment by YuechengLiu** [comment]
> Hi, thank you for providing such a great tool. I'm trying to extract the camera poses for each frame. But cam_data() fucntion is only supports static cameras, not character cameras. Is there a solution to get the parameters of the character camera or extract the camera pose for every frame? Thanks!

Hi, did you find a solution to do that? thanks!

**Comment by jaewonbae** [comment]
> > Hi, thank you for providing such a great tool. I'm trying to extract the camera poses for each frame. But cam_data() fucntion is only supports static cameras, not character cameras. Is there a solution to get the parameters of the character camera or extract the camera pose for every frame? Thanks!
> 
> Hi, did you find a solution to do that? thanks!

Yes, I did! 
You have to download the virtualhome_unity repository, modify the corresponding source code, and then build a new executable. Open the virtualhome_unity\Assets\Story Generator\Scripts\Recorder.cs file and uncomment line 278, which will save the camera pose for every frame. Please refer to the [virtualhome_unity repository](https://github.com/xavierpuigf/virtualhome_unity) for how to build executable. 
Good luck! :)
