### ISSUE TITLE
Not able to download the simulator executable

### ISSUE THREAD

**Issue by jigyasa27** [xavierpuigf/virtualhome#112]
[Download Unity Simulator](https://github.com/xavierpuigf/virtualhome#download-unity-simulator)
Download the VirtualHome UnitySimulator executable and move it under simulation/unity_simulator.

[Download](http://virtual-home.org//release/simulator/v2.0/v2.3.0/linux_exec.zip) Linux x86-64 version.
[Download](http://virtual-home.org/release/simulator/v2.0/v2.3.0/macos_exec.zip) Mac OS X version.
[Download](http://virtual-home.org//release/simulator/v2.0/v2.3.0/windows_exec.zip) Windows version.

All these 3 links for simulator download are not working, can you please check

**Comment by jigyasa27** [comment]
Able to download from command line

**Comment by cgxuvector** [comment]
The link issue mentioned above is still not resolved. But command line download works.

curl -O http://virtual-home.org/release/simulator/v2.0/v2.3.0/<your os>_exec.zip
