### ISSUE TITLE
There is no content when opening visualhome

### ISSUE THREAD

**Issue by Yaochangyu00** [xavierpuigf/virtualhome#113]
Hello!I would like to ask, I tried to run virtualhome on Linux. When I followed the steps, there was a problem with the operation. It stayed here without responding. (I have downloaded the corresponding linux.exec file, and the path is correct). In addition, even if I pass the "./path_to_exec -screen-fullscreen 0 -screen-quality 4" command, what is opened is a black interface with no content. I want to know why? How should I solve it?Thank you！
```
YOUR_FILE_NAME ="/home/yu/linux_exec/linux_exec.v2.2.4.x86_64"
>>> comm=simulation.unity_simulator.UnityCommunication(file_name=YOUR_FILE_NAME)
['/home/yu/linux_exec/linux_exec.v2.2.4.x86_64', '-batchmode', '-http-port=8080', '-logFile /home/yu/Virtual/virtualhome/virtualhome/Player_8080.log']
Getting connection...

```

**Comment by liuzl** [comment]
Same thing for me on windows:
> I pass the "./path_to_exec -screen-fullscreen 0 -screen-quality 4" command, what is opened is a black interface with no content.

**Comment by Yaochangyu00** [comment]
> 我在 Windows 上也遇到同样的情况：
> 
> > 我通过“./path_to_exec -screen-fullscreen 0 -screen-quality 4”命令，打开的是一个黑色的界面，没有任何内容。

> Hello, have you solved this problem?

**Comment by UltiSpike** [comment]
> > Hello, have you solved this problem?  

I meet the same

**Comment by bryanzhou008** [comment]
same for me on mac...

**Comment by Arpitrf** [comment]
I have the same problem

**Comment by cgxuvector** [comment]
Same problem

**Comment by henrycjh** [comment]
Cause this is just starting a simulator that is empty... You will see the content if you set it in your script.

**Comment by Lhyshining** [comment]
Firstly I use `./path_to_exec -screen-fullscreen 0 -screen-quality 4` to open virtual home manually. Then run `comm = comm_unity.UnityCommunication()` to connect virtual home server. Finally, set env and show camara by `comm.reset(env_id)` `s, cam_count = comm.camera_count()` `s, images = comm.camera_image([0, cam_count-1])`

**Comment by Zakkery0908** [comment]
> same for me on mac...

have you solved this problem?

**Comment by naiyouFF** [comment]
当你在终端运行命令后，显示完unity的图标之后就没有什么画面了，然后你到demo/unity_demo.ipynb中运行Starting and Visualizing Scenes之后的代码，就可以看到画面了
