### ISSUE TITLE
There are some errors when I use the expand_scene function

### ISSUE THREAD

**Issue by qyx1121** [xavierpuigf/virtualhome#114]
Hello, I downloaded the Activity Knowledge Base dataset from RobotHow and attempted to initialize the scene based on the files in the "init_and_final_graphs" folder. However, I consistently encountered some issues. 

The version of Virtualhome I used is v2.3.0. 

The code I used is as follows：
```
import json
program_path = "~/virtualhome/robothow/programs_processed_precond_nograb_morepreconds/init_and_final_graphs/TrimmedTestScene1_graph/results_text_rebuttal_specialparsed_programs_turk_robot/split90_3.json"
data = json.load(open(program_path))
graph = data["final_graph"]
comm.reset(0)
success, message = comm.expand_scene(graph)
message
```

The error message is as follows:
```Error processing input graph: Object reference not set to an instance of an object```

I would greatly appreciate your assistance in resolving this matter. Thank you!

**Comment by Kalcy-U** [comment]
Hi! I am facing the same problem, may I ask how you solved it?

**Comment by harshg99** [comment]
Hi, I am facing the same problem too.

**Comment by xiuxiusen** [comment]
the same problem,too,how you solved it?

**Comment by aaa393** [comment]
hi！I am facing the same problem,how  you solved it?

**Comment by DDLhaodong** [comment]
the same problem

**Comment by Control-derek** [comment]
the same problem, how you solved it?
