### ISSUE TITLE
Option to add robotic character

### ISSUE THREAD

**Issue by pradippramanick** [xavierpuigf/virtualhome#12]
Looking at the comm_unity.py file, I can see that the default character chosen is 'Chars/Male1'. Could you please provide some API to access the list of available characters? Also, if not already available can a humanoid / some other robot can be added to the characters?

**Comment by xavierpuigf** [comment]
Hi, in the branch `virtualhome_pkg`, you can see the list of available characters, and an API to add these into the simulator. We are finishing up that branch before integrating with the main branch. We currently do not have any robot, but we released the unity source code for VirtualHome. Feel free to add it there!
