### ISSUE TITLE
Share unity source

### ISSUE THREAD

**Issue by wetoo-cando** [xavierpuigf/virtualhome#13]
Hello Xavier,

Great work on this simulator! 

I would like to use it for research on Human Activity Analysis. Is it possible for you to share the source for the Unity simulator? There are several things I would like to change. Some examples:

- Lighting
- Direct control over cameras
- Control over 3D pose of a newly inserted object
- Additional sensors (IMU e.g.)
- Other apartments
- Multiple characters

If you can provide a greater degree of control over the Unity sim, I think it will help a lot of researchers get the most out of virtualhome.

Best,
Rahul

**Comment by xavierpuigf** [comment]
Hi @wetoo-cando. The source code for Unity can be found here: https://github.com/xavierpuigf/virtualhome_unity

**Comment by lmz123321** [comment]
@wetoo-cando Hi, have you managed to change the lighitng of virtual-home? 

I hopt to do the same thing. Could you give me some hint of how to modify the source code? Many thanks.

**Comment by wetoo-cando** [comment]
Unfortunately I had to stop working on this many years ago. Sorry, I can’t help you.
