### ISSUE TITLE
Export apartments as Unity assets

### ISSUE THREAD

**Issue by MohameHassan** [xavierpuigf/virtualhome#14]
Amazing work!
I would like to download the apartments and use them in another Unity project. I just need the apartments assets for now and nothing else. Could you tell me where can I download that from? Do I still need to install and run the simulator?

Thanks!

**Comment by xavierpuigf** [comment]
Hi @MohameHassan, you can find the Assets in the Unity Repository https://github.com/xavierpuigf/virtualhome_unity. Look at third_party.md
