### ISSUE TITLE
Error While adding character

### ISSUE THREAD

**Issue by NarinderBrar** [xavierpuigf/virtualhome#15]
Hi, I am trying to add character according to the QuickStart guide, But got the following error.
'UnityCommunication' object has no attribute 'add_character'

![tempsnip](https://user-images.githubusercontent.com/5476335/93501829-949a2600-f933-11ea-9a46-229ba5f663b9.png)

Can you please check if I miss something?
Thanks

**Comment by xavierpuigf** [comment]
Hi @NarinderBrar, the code to add characters is still in beta, and it is not in the main branch. You can find it in `virtualhome_pkg` branch.

**Comment by NarinderBrar** [comment]
Thanks, Yes comm_unity.py have the functionality to add a new character, but its response return "false". Same with add_camera, the response is (False, 'Unknown action add_camera'). 

Do that mean I also need to download some other version of Unity build?

**Comment by xavierpuigf** [comment]
Indeed, the updates require a new simulator, you can find it below. Please note that this build is still in beta, we are actively developing it and will soon be pushed to master :). You can find the source code of the simulator here: https://github.com/xavierpuigf/virtualhome_unity

For MacOS: http://virtual-home.org/release/simulator/v2.0/exec_macos.zip
For Linux: http://virtual-home.org/release/simulator/v2.0/exec_linux.zip

**Comment by NarinderBrar** [comment]
Ok, Thanks 
I will check it.
