### ISSUE TITLE
How stream data could be saved

### ISSUE THREAD

**Issue by snitchjinx** [xavierpuigf/virtualhome#18]
Hello Xavier, thanks for the awesome project!

I'm new to Unity but would like to build my own dataset with this project. My dataset would require joint positions of human poses in addition to the rendered videos. Would you provide some guidance about how can I save such customized stream data based on this repo?

Thank you for your consideration!

**Comment by xavierpuigf** [comment]
Hi @snitchjinx. The use case you are mentioning is included in VirtualHome. You need to run the function `render_script`, shown here: https://github.com/xavierpuigf/virtualhome/blob/master/simulation/unity_simulator/comm_unity.py#L235

The field `image_synthesis` indicates the modality you want to save the frames in: you can save optical flow, rgb, semantic segmentation etc at the same time. `camera_mode` indicates the camera in which you want to render the scripts. Finally, to save the 3d keypoints, you can just run `save_pose_data`. It will save the keypoints of the characters in your videos, for every frame.

Hope this helped!

**Comment by snitchjinx** [comment]
Hello Xavier, thank you for your reply!

I tried to set `save_pose_data=True` in function `render_script`, and run ./demo/generate_video.py. I can find the rendered video frames in ./simulation/unity_simulator/Output/script, but no corresponding saved poses.

I wonder did I miss anything? Thank you~

**Comment by xavierpuigf** [comment]
Hi, could you see if inside the script there is a file called `pd_script.txt`? That should contain the pose data. If not, could you tell me the commands you are using? I would try to reproduce it.

**Comment by xavierpuigf** [comment]
Hi included in the demo notebook a script to recover and render the pose data. You should be able to get a 3D plot with the pose from a given frame.
