### ISSUE TITLE
How to set First Person View?

### ISSUE THREAD

**Issue by yunsujeon** [xavierpuigf/virtualhome#19]
Hello Xavier, thanks for your project

I have a question to generating video.
I want to play and save video by **first person view.**
like this : https://www.shutterstock.com/video/clip-4622975-first-person-view-walking-on-bridge

How can i do it? on uniy_demo.ipynb

**Comment by xavierpuigf** [comment]
Hi, you can save the first person view by adding that camera into `camera_mode` in render_script. If you set the mode to `"FIRST_PERSON"`, you should get a first person view for the video. Note that you can also use indices of cameras, if you want a fixed camera in the apartment, and you can introduce multiple cameras at the same time.

**Comment by yunsujeon** [comment]
Thanks for your reply! i'll try it
