### ISSUE TITLE
cannot render_script

### ISSUE THREAD

**Issue by jolinxql** [xavierpuigf/virtualhome#2]
Hi, 
I can successfully run all scripts in [unity_demo.ipynb](https://github.com/xavierpuigf/virtualhome/blob/master/demo/unity_demo.ipynb) **except lines containing `render_script`.**
I always get the following error when I try to `render_script`:
```
------------------------------------------------------------
UnityEngineException       Traceback (most recent call last)
<ipython-input-33-b0a2016e0ac0> in <module>()
     13                                       image_width=512, image_height=320,
     14                                       file_name_prefix='milk',
---> 15                                       camera_mode='FIRST_PERSON')

~/Source/virtualhome/simulation/unity_simulator/comm_unity.py in render_script(self, script, randomize_execution, random_seed, processing_time_limit, skip_execution, find_solution, output_folder, file_name_prefix, frame_rate, image_synthesis, capture_screenshot, save_pose_data, image_width, image_height, gen_vid, save_scene_states, character_resource, camera_mode)
    141                   'image_width': image_width, 'image_height': image_height}
    142         response = self.post_command({'id': str(time.time()), 'action': 'render_script',
--> 143                                       'stringParams': [json.dumps(params)] + script})
    144         if response['success']:
    145             if gen_vid and len(image_synthesis) > 0:

~/Source/virtualhome/simulation/unity_simulator/comm_unity.py in post_command(self, request_dict)
     19             resp = requests.post(self._address, json=request_dict)
     20             if resp.status_code != requests.codes.ok:
---> 21                 raise UnityEngineException(resp.status_code, resp.json())
     22             return resp.json()
     23         except requests.exceptions.RequestException as e:

UnityEngineException: (408, {'id': '1561703596.590129', 'success': False, 'message': 'Timeout', 'value': 0, 'message_list': None})
```
I'm using Ubuntu 18.04 remotely.
I have also tried docker. I can run [generate_snapshot.py](https://github.com/xavierpuigf/virtualhome/blob/master/demo/generate_snapshot.py) inside or outside the docker and successfully get all the snapshots.
But I always get the same error when running [generate_video.py](https://github.com/xavierpuigf/virtualhome/blob/master/demo/generate_video.py), always stuck at `render_script` function.
Could you please help me?

**Comment by xavierpuigf** [comment]
Hi @jolinxql, 

This is probably due to the fact that you are generating a high quality video for the script, which takes too long for your gpu. Could you try tendering only the first element in the script? You can set script = [script[0]]. If this runs well and generates the video, you may need to reduce the quality of the video you are generating, or it's framerate. Some of the things you can try to generate the whole script.

- Run the executable with a lower quality. Check out screen-quality [here](https://docs.unity3d.com/Manual/CommandLineArguments.html). Options are -Fastest -Fast -Simple -Good -Beautiful -Fantastic
- Reduce the frame height and width 
- Lower the frame_rate: set the flag frame_rate to e.g. 10 in render_script

Let me know if that works.

**Comment by jolinxql** [comment]
Thank you @xavierpuigf , 

I tried using the script = ['[Walk] <sofa> (1)'], lowest video quality(Fastest), lower frame_rate (1,2,3,4,5), lower height and width (e.g.,640x480-->60x40). Unfortunately, I still got the same error. The command I tried:
```bash
./unity_vol/executable_march19/synvid.x86_64 -batchmode \
-screen-width=60 -screen-height=40 \
-screen-quality=Fastest -http-port=8080
```
A minimal working example:
```python
# Generate video for a program. Make sure you have the executable open
import sys
sys.path.append('../simulation/')
from unity_simulator.comm_unity import UnityCommunication
script = ['[Walk] <sofa> (1)'] # Add here your script
print('Starting Unity...')
comm = UnityCommunication(port='8080')
print('Starting scene...')
comm.reset()
print('Generating video...')
comm.render_script(script, frame_rate=2, find_solution=True, output_folder='Output/',
                   image_width=60, image_height=40)
```
Output from python:
```
Starting Unity...
Starting scene...
Generating video...
Traceback (most recent call last):
  File "/home/nav/virtualhome/demo/generate_video.py", line 13, in <module>
    image_width=640, image_height=480)
  File "/home/nav/virtualhome/simulation/unity_simulator/comm_unity.py", line 143, in render_script
    'stringParams': [json.dumps(params)] + script})
  File "/home/nav/virtualhome/simulation/unity_simulator/comm_unity.py", line 21, in post_command
    raise UnityEngineException(resp.status_code, resp.json())
unity_simulator.comm_unity.UnityEngineException: (408, {'id': '1562026763.45415', 'success': False, 'message': 'Timeout', 'value': 0, 'message_list': None})
```
Output in the terminal (unity3d simulator):
```
Set current directory to /
Found path: /unity_vol/executable_march19/synvid.x86_64
Mono path[0] = '/unity_vol/executable_march19/synvid_Data/Managed'
Mono config path = '/unity_vol/executable_march19/synvid_Data/MonoBleedingEdge/etc'
Display 0 '0': 640x480 (primary device).
Logging to /root/.config/unity3d/VirtualHome/VH01/Player.log
^CXIO:  fatal IO error 0 (Success) on X server ":99"
      after 269 requests (269 known processed) with 0 events remaining.
```
Other info:
GPU: GeForce RTX 2080 Ti
[/root/.config/unity3d/VirtualHome/VH01/Player.log](https://github.com/xavierpuigf/virtualhome/files/3347731/Player.log)

**Comment by xavierpuigf** [comment]
Thanks for the info, when did you download the executable? In a previous executable, the `image_synthesis` flag was binary,. The current executable expects that flag to be a list of strings: `['normal']`. Could you try downloading the Unity executable and run again?

Could you try for now running outside of docker? I will check if there may be a problem with docker too.

**Comment by jolinxql** [comment]
Thanks for your prompt reply. It works now! I download the newest executable and set `processing_time_limit=100` like this
```
comm.render_script(script, processing_time_limit=100,
                   find_solution=True, output_folder='Output/',
                   image_width=640, image_height=480)
```
`processing_time_limit=10` is to small for my environment, `processing_time_limit=100` is perfect.

**Comment by xavierpuigf** [comment]
Great! Closing this issue.
