### ISSUE TITLE
How to generate a video output

### ISSUE THREAD

**Issue by Lsbryant** [xavierpuigf/virtualhome#20]
Hi Xavier. 

I am Bryant, we had contacted via email before.  Could you show more details about how to generate as a video output(such .mp4), instead of a bunch of *.png format of images? Here is a screenshot of the error message on the python.

Thank you!
![捕获](https://user-images.githubusercontent.com/58193449/105767007-1b818f80-5f20-11eb-9bfd-aea9bb358648.PNG)

**Comment by xavierpuigf** [comment]
Hi Bryant,

It may be that your frames are being saved in a different than expected. In particular, they should be in a folder which is in the same directory as the executable. Is this the case? Note that this code assumes that this is inside `unity_simulator`. If that is not the case, you should change the path here.
https://github.com/xavierpuigf/virtualhome/blob/master/simulation/unity_simulator/comm_unity.py#L288

**Comment by xavierpuigf** [comment]
Hi @Lsbryant, I updated the `unity_demo.ipynb` with an example showing how to render a video. Closing the issue for now.
