### ISSUE TITLE
docker problem

### ISSUE THREAD

**Issue by onlyonewater** [xavierpuigf/virtualhome#21]
Hi, @xavierpuigf ,when I use Run the Docker container command, I got the following error: 

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./run_sim.sh\": permission denied": unknown.
ERRO[0001] error waiting for container: context canceled

How can I solve it?

**Comment by onlyonewater** [comment]
oh, when I add RUN chmod +x run_sim.sh before ENTRYPOINT command, rebuild the Dockerfile, and run command again, I got another error:

standard_init_linux.go:211: exec user process caused "exec format error"

How can I solve it?

**Comment by xavierpuigf** [comment]
Hi @onlyonewater , could you check if the executable you are using is the one listed here? https://github.com/xavierpuigf/virtualhome/blob/master/docker/run_sim.sh

Remember you need to download the executable

**Comment by onlyonewater** [comment]
Yes, I check it. There is no problem. but now I use windows version, It can run successfully.

**Comment by donggehan** [comment]
Hi @onlyonewater @xavierpuigf  I am encountering the same error "exec user process caused "exec format error"" on linux after adding RUN chmod +x run_sim.sh   before the entry point. Can you advice me how this can be resolved? Thank you!

**Comment by Arpitrf** [comment]
I am getting this same error!
