### ISSUE TITLE
Env get observation bug. 

### ISSUE THREAD

**Issue by KaixiangLin** [xavierpuigf/virtualhome#22]
This line setting 
```
mode = obs_type
```
will cause returning image failed. 

https://github.com/xavierpuigf/virtualhome/blob/8f6f5575909302f2d54a9627d595b5a133cdbabe/simulation/environment/unity_environment.py#L267

It seems mode value should be one of follows for acquiring valid image.
```
{ "normal", "seg_inst", "seg_class", "depth", "flow", "albedo", "illumination", "surf_normals" }
```

**Comment by xavierpuigf** [comment]
Thank you! This should be fixed in the latest commit
https://github.com/xavierpuigf/virtualhome/commit/9e4ed85c9ed9eaa0ec56cfa04b6b469130c62c1d
