### ISSUE TITLE
windows simulator problem

### ISSUE THREAD

**Issue by onlyonewater** [xavierpuigf/virtualhome#23]
Hi, when I use the windows simulator, I download the windows simulator, and unzip it, it shows the following mistakes:
1	windows_exec\2013_10 - Sample Assets_Data\GI\level2\c1\c16dfef465f71ce8089721383f9513ef.rsc.sse: CRC check error, the file is damaged	C:\Users\USER\Downloads\windows_exec.zip
2	windows_exec\2013_10 - Sample Assets_Data\sharedassets0.assets.resS: CRC check error, the file is damaged	C:\Users\USER\Downloads\windows_exec.zip
3	windows_exec\2013_10 - Sample Assets_Data\resources.assets.resS: CRC check error, the file is damaged	C:\Users\USER\Downloads\windows_exec.zip

can you upload the windows simulator again?? My system is windows 10.

**Comment by xavierpuigf** [comment]
Hi, can you point me to the link where you are downloading from? I managed to unzip without problems.

**Comment by onlyonewater** [comment]
oh, I Download Windows version from here:
![image](https://user-images.githubusercontent.com/41667733/106007642-7a4a3300-60f1-11eb-9458-9b7037d2c50d.png)

**Comment by xavierpuigf** [comment]
I managed to unzip that on a linux and macOS, but I unfortunately don't have a windows OS to test that at the moment. Will be uploading the executable again today.

**Comment by xavierpuigf** [comment]
I zipped a new version, could you check if that works?

**Comment by onlyonewater** [comment]
oh, I download it again, and now it has no problem. Thanks!!!
