### ISSUE TITLE
about make videos

### ISSUE THREAD

**Issue by yunsujeon** [xavierpuigf/virtualhome#24]
Hi xavier,
I have questions about make videos

1. Can I make Segmentation video? 
In camera modes -> modes = ['normal', 'seg_class', 'surf_normals'] so I can make seg_class capture. but in video..?

2. Can i make low view video? 
In comm, render_script has [automatic (AUTO), first person (FIRST_PERSON), top (PERSON_TOP)] view. Can i set the camera mode? like puppy's sight?

3. Can i get labeling data?
I wanna training object detection on this simulation..
![Screenshot from 2021-01-29 11-12-55](https://user-images.githubusercontent.com/38097792/106223021-02305a00-6224-11eb-9b73-602134c2cede.png)
is this labeling data? (augmentation data?)

thank you

**Comment by xavierpuigf** [comment]
Hi @yunsujeon, you can use the same camera modes that you use for images in videos, they will generate videos with multiple modes and camera views. Notice that in videos, you can actually generate videos from multiple cameras at the same time. You can see how this is done in the demo code.

Currently you can add static cameras in the scene and generate from those (indicating the camera number), or you can generate videos from the character cameras, which include:
`[FIRST_PERSON, PERSON_TOP, PERSON_FROM_BACK, PERSON_FROM_LEFT, PERSON_FRONT]`

I may add if needed a way to add new cameras that are attached to the character.

The data you are pointing to allows to generate images, but not videos unfortunately. You can generate videos though with the data from our latest watch and help paper: http://virtual-home.org/release/watch_and_help/watch_data.zip. You will see a sequence of programs that you can render and obtain semantic segmentation. From there you can train a model for object detection.

Hope this helps

**Comment by yunsujeon** [comment]
Thank you for reply!
I run a demo code unity_demo.ipynb, The automatic (AUTO) option generate video on low sight. but it is multiple camera..
I want static low sight camera like [FIRST_PERSON, PERSON_TOP, PERSON_FROM_BACK, PERSON_FROM_LEFT, PERSON_FRONT] + **PERSON KNEE SIGHT** 
Is this impossible?

**Comment by xavierpuigf** [comment]
Hi! I will work this coming week on a function to add cameras attaches to characters, so that you can specify the relative position of the camera. Will write here when it is done!

**Comment by yunsujeon** [comment]
Thank you so much! that's what i needed

**Comment by xavierpuigf** [comment]
Hi Yunsujeon, we added in the new release the ability to add character cameras. In particular, you can call

`comm.add_character_camera(name="the_camera_name", position={pos}, rotation={rot})`

This will define a new camera that will be attached to every new character you add in the scene. You can then call render_script with that camera name in order to record from a new point of view. You can check the current character cameras defined by running `comm.character_cameras()`, which will return the list of cameras defined.

I hope that helps!
