### ISSUE TITLE
Can I use your simulator to create my own data set?

### ISSUE THREAD

**Issue by onlyonewater** [xavierpuigf/virtualhome#25]
Hi, Can I use your simulator to create my own dataset for my paper? We will cite the three papers you listed.

**Comment by xavierpuigf** [comment]
For sure, feel free to create your own dataset. We have a planner in our latest [watch_and_help](https://github.com/xavierpuigf/watch_and_help) paper that allows generating a dataset with a single or multiple agents, but you can also manually build the actions yourself. Let me know if you need any additional information.

**Comment by onlyonewater** [comment]
OK, I get it, If I have any questions, I will contact you again. Thanks!!!
