### ISSUE TITLE
How to generate a video(.mp4) output

### ISSUE THREAD

**Issue by onlyonewater** [xavierpuigf/virtualhome#26]
Hi, @xavierpuigf , when I use your unity_demo.ipynb, I can't get video output, it reminded me that The input path: ../simulation/Output/ you specified does not exist. Why? and my frame files are inside **unity_simulator** file.
![image](https://user-images.githubusercontent.com/41667733/108968124-56134f00-76bb-11eb-8376-e930945093f2.png)

**Comment by onlyonewater** [comment]
And if I use path_video = "../simulation/unity_simulator/windows_exec/Output", it reported an error: FileNotFoundError: [WinError 2] The system cannot find the specified file

**Comment by onlyonewater** [comment]
The full errors are as following:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-60-fd166e7bcd37> in <module>
      2 # path_video = "../simulation/Output"
      3 path_video = "E:\\virtualhome\\simulation\\unity_simulator\\Output"
----> 4 utils_viz.generate_video(input_path=path_video, prefix='relax', output_path="E:\\virtualhome\\simulation\\Output")

E:\virtualhome\simulation\unity_simulator\utils_viz.py in generate_video(input_path, prefix, char_id, image_synthesis, frame_rate, output_path)
     18                              '{}/Action_%04d_0_{}.png'.format(vid_folder, vid_mod),
     19                              '-framerate', str(frame_rate),
---> 20                              '-pix_fmt', 'yuv420p',
     21                              '{}/video_{}.mp4'.format(output_path, vid_mod)]
     22             subprocess.call(command_set)

d:\anaconda3\envs\virtualhome\lib\subprocess.py in call(timeout, *popenargs, **kwargs)
    337     retcode = call(["ls", "-l"])
    338     """
--> 339     with Popen(*popenargs, **kwargs) as p:
    340         try:
    341             return p.wait(timeout=timeout)

d:\anaconda3\envs\virtualhome\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

d:\anaconda3\envs\virtualhome\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1205                                          env,
   1206                                          os.fspath(cwd) if cwd is not None else None,
-> 1207                                          startupinfo)
   1208             finally:
   1209                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the specified file

**Comment by gkj23** [comment]
Did you already solved this issue? I'm facing the same issue now!

**Comment by vllbc** [comment]
Did you already solved this issue?

**Comment by gkj23** [comment]
> Did you already solved this issue?
好像是要改一下生成video的路径，我改完就可以生成了，实在不行也可以自己写脚本把生成的每帧图片合起来（看你是苏州大学的我就直接用中文了）

**Comment by vllbc** [comment]
> > Did you already solved this issue?
> > 好像是要改一下生成video的路径，我改完就可以生成了，实在不行也可以自己写脚本把生成的每帧图片合起来（看你是苏州大学的我就直接用中文了）

谢谢您的解答，十分感谢
