### ISSUE TITLE
Which folder contains data for ActivityPrograms

### ISSUE THREAD

**Issue by shuyanzhou** [xavierpuigf/virtualhome#29]
Hi, 

The paper https://arxiv.org/pdf/1806.07011.pdf describes two datasets, one is ActivityProgram and the other is VirtualHome Activity. 

After downloading the dataset, I found there are multiple folders inside the ``withoutconds`` folder:

 ```
withoutconds
├── results_intentions_march-13-18
├── results_text_rebuttal_specialparsed_programs_turk_july
├── results_text_rebuttal_specialparsed_programs_turk_robot
├── results_text_rebuttal_specialparsed_programs_turk_third
├── results_text_rebuttal_specialparsed_programs_upwork_july
├── results_text_rebuttal_specialparsed_programs_upwork_kellensecond
└── results_text_rebuttal_specialparsed_programs_upworknturk_second
```

I am wondering which files/folders are for ActivityPrograms?

Thanks!

**Comment by xavierpuigf** [comment]
Hi @shuyanzhou,

The folder that you downloaded here corresponds to our second work on predicting programs from activity sketches. http://virtual-home.org/paper/env_program.pdf

The datasets you are referring can be found in the following links. I will update the repository accordingly.
ActivityProgram: 
http://virtual-home.org/release/programs/virtualhome_cvpr18/real.zip

VirtualHome Activity:
http://virtual-home.org/release/programs/virtualhome_cvpr18/synthetic.zip
