### ISSUE TITLE
Executable not updating scene

### ISSUE THREAD

**Issue by dtsbourg** [xavierpuigf/virtualhome#3]
# Description 

Hi @xavierpuigf ! I'm having an issue running the linked executable file. Specifically, the simulator does not seem to refresh / render the scene (the screen is just gray) unless I manually fetch the camera view from within the Jupyter notebook. No keyboard input is detected either.

# Metadata

- Mac OSX 10.14.6 on MacBook Pro 15" (Radeon Pro 4GB GPU + Intel UHD Graphics 630, 2.2GHz i7 CPU)
- Binary downloaded from provided link on Aug 19th
- Ran provided example scene

# Steps to reproduce

0. git clone `virtualhome`
1. `pip3 install -r requirements.txt`

> No errors except for a version mismatch:
> `ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.3 which is incompatible.`
> Replaced by `requests 2.22.0`
 
2. Download `mac_sim.zip` 
3. Unzip and place in the `simulation` folder (also tried the download script)
4. Run executable with specified settings (resolution + quality + windowed)
5. App starts up, logo unity shows then the screen just stays gray / black
6. Open Jupyter notebook (`unity_demo.ipynb`)

> Here again no major errors, a little problem with plotly but probably unrelated
 
```
ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 
```
7. Step through notebook
8. `comm = setup()` fails at first because the package has to be correctly renamed (by default the unzipped `.app` seems to be named `exec_mac_07_01.app` and not `exec_mac.app` as expected.
9. Image viz seems to work (though lacking the last cell on the bottom right
10. `comm.reset(4)` returns `True`
11. `display_scene_cameras` call triggers an update to the executable app, which now shows the top view of the bathroom (the last cell on the bottom right, probably the same that didn't appear in step 9)
12. `display_scene_modalities` works and also triggers a view update, this time to show the view of the character (right-most cell, RGB camera view)

Other: Adding objects works, but here again `get_scene_cameras` is the only function call that updates the view in the executable.

Thanks for your help :)

**Comment by xavierpuigf** [comment]
Hello,

If I understood correctly, the issue is that you can only see the updated scene when fetching the camera. This is actually the expected behavior. The scene state changes as you add/remove or change the state of objects, as you will see if you read the graph with `comm.environment_graph()`. If you want to see the changes, you need to call `comm.camera_image(indices)` where indices are the indices of the cameras you want to check.

Hope this helps!
Best,
Xavier
