### ISSUE TITLE
How can I access the images/videos as well as 3D groundtruth of frames in your datase?

### ISSUE THREAD

**Issue by monacv** [xavierpuigf/virtualhome#31]
I downloaded your dataset but the files that it contains are only txt and json files. How can I access the videos/frames of your dataset as well as the 3D groundtruth and instance segmentation mask for each object in every frame of your dataset?

```
mona@goku:~/research/data/virtual_home_dataset/programs_processed_precond_nograb_morepreconds$ find . -type f | perl -ne 'print $1 if m/\.([^.\/]+)$/' | sort -u
json
txt
mona@goku:~/research/data/virtual_home_dataset/programs_processed_precond_nograb_morepreconds$ ls
total 28K
drwxrwxr-x 9 mona mona 4.0K Feb 13  2019 withoutconds
drwxrwxr-x 9 mona mona 4.0K Feb 13  2019 initstate
drwxrwxr-x 7 mona mona 4.0K Mar 15  2019 .
drwxrwxr-x 9 mona mona 4.0K Mar 15  2019 state_list
drwxrwxr-x 9 mona mona 4.0K Mar 15  2019 init_and_final_graphs
drwxrwxr-x 9 mona mona 4.0K Mar 15  2019 executable_programs
drwxrwxr-x 3 mona mona 4.0K Mar 31 02:09 ..
```

**Comment by kswain98** [comment]
> I downloaded your dataset but the files that it contains are only txt and json files. How can I access the videos/frames of your dataset as well as the 3D groundtruth and instance segmentation mask for each object in every frame of your dataset?
> 
> ```
> mona@goku:~/research/data/virtual_home_dataset/programs_processed_precond_nograb_morepreconds$ find . -type f | perl -ne 'print $1 if m/\.([^.\/]+)$/' | sort -u
> json
> txt
> mona@goku:~/research/data/virtual_home_dataset/programs_processed_precond_nograb_morepreconds$ ls
> total 28K
> drwxrwxr-x 9 mona mona 4.0K Feb 13  2019 withoutconds
> drwxrwxr-x 9 mona mona 4.0K Feb 13  2019 initstate
> drwxrwxr-x 7 mona mona 4.0K Mar 15  2019 .
> drwxrwxr-x 9 mona mona 4.0K Mar 15  2019 state_list
> drwxrwxr-x 9 mona mona 4.0K Mar 15  2019 init_and_final_graphs
> drwxrwxr-x 9 mona mona 4.0K Mar 15  2019 executable_programs
> drwxrwxr-x 3 mona mona 4.0K Mar 31 02:09 ..
> ```

Hi @monacv! You will need to use the scripts provided to generate the data with the corresponding VirtualHome executable file.
