### ISSUE TITLE
SLEEP is not executable

### ISSUE THREAD

**Issue by Ease112** [xavierpuigf/virtualhome#34]
I tried to run the below script.
```
script = ['[Walk] <bedroom> (1)', '[Walk] <bed> (1)', '[Lie] <bed> (1)', '[Sleep]']
preconds = add_preconds.get_preconds_script(script).printCondsJSON()
g = check_programs.translate_graph_dict_nofile(g)
info = check_programs.check_script(script, preconds, graph_path=None, inp_graph_dict=g)
message, final_state, graph_state_list, graph_dict, id_mapping, info, helper, executed_script = info
print(message)
```

I got this error message, but the 'Lie' exists before the 'Sleep' in this script.
`'Script is not executable, since <character> (1) is not lying or sitting when executing "[SLEEP] [4]"'`

**Comment by kswain98** [comment]
Hi @Ease112! I am working on a fix for this action, it will take me a few days to get this done. I will let you know when it's fixed.

**Comment by kswain98** [comment]
Hi @Ease112 ! I am currently fixing this issue for another project, I will let you know when it's fixed!

**Comment by kswain98** [comment]
@Ease112 Sleep is not a working action in the unity version but might be added when we have time. Sorry for the 1 year delay!
