### ISSUE TITLE
issues in ‘auto’ mode for communication

### ISSUE THREAD

**Issue by yinyunie** [xavierpuigf/virtualhome#35]
Hi,

Thanks a lot for this super cool repository. I tried to use 'auto' mode for communication like below in your 'unity_demo.ipynb':

```
mode = 'manual' # auto / manual
if mode == 'auto':
    if platform == 'darwin':
        exec_file = '../simulation/macos_exec'
    else:
        exec_file = '../simulation/exec_linux.x86_64'
    comm = UnityCommunication(file_name=exec_file)
else:
    comm = UnityCommunication()
```
but the code is freezing as
```
['/home/ynie/github/virtualhome/simulation/unity_simulator/linux_exec.x86_64', '-batchmode', '-http-port=8080', '-logFile /home/ynie/github/virtualhome/Player_8080.log']
Getting connection...
```

Could you please help with this?

Thanks a lot.

Best,
Yinyu

**Comment by xavierpuigf** [comment]
Hi Yinyu,

Are you running this on your desktop or a headless server? If you are running it on a desktop, could you check that the unity executable is opening? If it is on a server, could you try running it with `no_graphics=True`? If that works, we can look later at how to get the graphics working.

**Comment by yinyunie** [comment]
Thanks for your reply.

I run it on desktop. Do you mean I still need to 'manually' open the unity executable if I choose the 'auto' mode? Thanks a lot for your help.

Best,
Yinyu

**Comment by xavierpuigf** [comment]
Hi! In MacOS I have experienced some issues with opening executables automatically, generally due to permission errors. If you are running it on MacOS on a desktop, I would recommend you to use the manual mode. If you work on a server, the auto mode should work fine.

**Comment by aarbelle** [comment]
Hi, 
I am also having the same issues, I am working on a headless linux server. 
After adding `no_graphics=True`  I get the "Got connection..." response.. 
However, now the following block just shows a gray screen:
```indices = [3, 32, -5, -1, -20, 15, 48, -8]
img_final = display_scene_cameras(comm, indices, nrows=2)
IPython.display.display(img_final)```

**Comment by xavierpuigf** [comment]
Hi @aarbelle, if you have a headless server, you should make sure you are running a virtual display. For that, open a new terminal, making sure you are in the same node where you want to run the simulator, and run

```
sudo python helper_scripts/startx.py $display_num
```

Make sure the display_num matches the number you add when you create the UnityCommunication object. Let me know if you run into further issues

**Comment by aarbelle** [comment]
Hi, 
Thanks for the response,
Unfortunately I don't have sudo permissions on the server,
I can however start a vnc server on a different node. If that is in any way helpful. 
Is there anything I can do without sudo?

**Comment by xavierpuigf** [comment]
Could you try to run it without sudo? VNC would allow you to visualize what is being rendered, but I am afraid you still need an Xserver to do rendering. It may be that you can run the Xserver without sudo though. Or maybe the Xserver is already running. You could check that if you run

```
ps -aux | grep Xorg
```

and see if that shows any process

**Comment by aarbelle** [comment]
Hi, 
So I see that the Xorg process is running. What should I do next?

**Comment by xavierpuigf** [comment]
Oh, this refers to the grep command that you were already running, not the Xorg program itself. From this output, it seems like Xorg is not running.
Is there anyway you can get someone with sudo access to run this for you? Otherwise, here is a pointer on running this without sudo: https://unix.stackexchange.com/questions/315169/how-can-i-run-usr-bin-xorg-without-sudo

**Comment by kswain98** [comment]
Hi @aarbelle! Where you able to fix the issue?
