### ISSUE TITLE
ScriptExcutor 0: PROCESS WALK: Can not select object: garbagecan. REASON: Unknown EXECUTION_GENERAL: Script is impossible to execute

### ISSUE THREAD

**Issue by Ne94fets** [xavierpuigf/virtualhome#36]
Hello, 
I was trying to execute the following single line script using `render_script()` in a fresh scene (idx 0):
```
script = ['<char0> [open] <garbagecan> (106)']
```

I got the following error message:
```
ScriptExcutor 0: PROCESS WALK: Can not select object: garbagecan. REASON: Unknown
EXECUTION_GENERAL: Script is impossible to execute
```
Afterwards the character is wiggling on the same position (see following image):
![Action_0000_0_normal](https://user-images.githubusercontent.com/19843921/123271854-85b75400-d501-11eb-8479-5b5f62a725fc.png)

I also checked that the preconditions to execute "open" are met in the scene graph. The scene graph says, that character is close to garbagecan and is holding nothing. I attached the scene graph. This also happens sometimes with other objects.

[scene_graph.txt](https://github.com/xavierpuigf/virtualhome/files/6709515/scene_graph.txt)
 
Am I missing a condition or is it a bug?
I am using VirtualHome 2.2.0 with the executables of Release 2.0.0 on Windows 10.

**Comment by Ne94fets** [comment]
I check the graph again and saw that the garbagecan is not in the same room as the character. I this maybe the missing condition?

**Comment by ddevleena** [comment]
I've been running into a lot of similar bugs such as these above in trying to simulate home routine activities. What's the best systematic way about approaching this? I tried downloading the sample programs on the RoboHow website but those seem outdated. For example <home_office> is not found in any of the homes? In general, I'm having no luck finding which rooms have which objects as well in the documentation. 

Any help would be much appreciated

**Comment by kswain98** [comment]
@ddevleena The best way to know which objects are in what room is to retrieve the coordinate of each room and then cross reference each object in the graph with the room coordinates. If the objects are inside this "virtual" area created by the coordinates then you can easily mark which objects are located in specific room. If you want I can share a snippet of my own code that you can try out.

**Comment by kswain98** [comment]
Hi @Ne94fets ! Thank you for bringing this up. The issue has now been fixed. There were colliders issues with certain objects (such as fruits, plates, cups, etc) in the previous environments.
