### ISSUE TITLE
Questions and Problems About VirtualHome

### ISSUE THREAD

**Issue by PeixinC** [xavierpuigf/virtualhome#40]
Hi, 
I tried to run the VirtualHome on Windows 10 with Conda environment but met some problems.
1. The link for the Windows executable provided in the README fails, so I download the executable from http://virtual-home.org/documentation/get_started/get_started.html#id4. I am not sure if these two executables are the same or not. Could you please fix the link?
2. When I run `comm = UnityCommunication(file_name=/path/to/windows_exec)`, I get the following error: Exception: Couldn't launch the windows_exec environment. Provided filename does not match any environments. I looked at the code in `launch_executable()` in communication.py and found that the code may not support Windows. I wonder if VirtualHome runs on Windows?

Thanks!

**Comment by xavierpuigf** [comment]
I just pushed an update that should allow to run the simulator on windows when specifying an executable file, please let me know if you find issues

**Comment by PeixinC** [comment]
Thanks for your answers!

Something about Question 2. I realized that VirtualHome supports Windows. Instead of providing path to the .exe file `comm = UnityCommunication(file_name=/path/to/windows_exec)`, I manually launched the .exe file and use `comm = UnityCommunication()` to create communication. It works. 

Question 3: We are wondering if we can use VirtualHome to create a Gym environment for our project but it seems there is no `test_unity_environment.py` in the demo folder.

Question 4: What is the best way for us to understand the scene? For example, what object is it or what objects are in a home? Should we git clone git clone https://github.com/xavierpuigf/virtualhome_unity.git and open the scene with Unity Editor?

Thanks!

**Comment by PeixinC** [comment]
I just test your new push. The condition for the platform should be `if platform=='win32'`. After this change, the program seems to work. I still need to manually launch the executable though. Will I manually launch the executable multiple times when, for example, multiple parallel VirtualHome are running for the RL training?

Thanks!

**Comment by xavierpuigf** [comment]
I would suggest getting a linux environment for the multi-instance setting, but I think it should still work on windows... It requires thought to launch them with the terminal though, so it would be good to figure why it is failing. What is the path you are using for the executable? Maybe you are not pointing to the .exe file?

**Comment by xavierpuigf** [comment]
Regarding Question 3: My bad, I did not push the testing files... I have those in a computer I don't have access to right now, but I will be pushing it tomorrow!

**Comment by PeixinC** [comment]
These are the commands I used
![image](https://user-images.githubusercontent.com/26445819/131585290-4f017497-6cf3-43fb-ba72-07333b31c9cc.png)

The program hung after the last command. It seems the program is waiting for the simulator but never gets connected. If I manually launch the executable, the communication can be established.

**Comment by xavierpuigf** [comment]
I see... The commands seem correct. It might be some permission issues on the executable, since you should at least see the executable opening when you launch this command.

**Comment by xavierpuigf** [comment]
I just pushed the gym-like environment tests, in case you want to take a look. Unfortunately, I don't have a windows OS at the moment, and cannot test further the issue with the executable. From your logs, and knowing that the executable never gets to open, I think it may be a permissions issue, but I cannot tell 100%.

**Comment by PeixinC** [comment]
Thank you for your response. We will probably use Linux when we train the RL agent.
