### ISSUE TITLE
Getting Connection Problem

### ISSUE THREAD

**Issue by CharlesQ9** [xavierpuigf/virtualhome#41]
I follow the instruction on http://virtual-home.org/documentation/get_started/get_started.html#installation

./simulation/unity_simulator/linux_exec/linux_exec.v2.2.4.x86_64 -screen-fullscreen 0 -screen-quality 4 

then python test.py where test.py is
'''
from simulation.unity_simulator import comm_unity
from simulation.unity_simulator.comm_unity import UnityCommunication
YOUR_FILE_NAME = "simulation/unity_simulator/linux_exec/linux_exec.v2.2.4.x86_64" 
comm = UnityCommunication(file_name=YOUR_FILE_NAME)
comm.reset(0)
success, image = comm.camera_image([0])
print(image[0].shape)
'''
The output information:
['/home/xxxxxxx/virtualhome-master/simulation/unity_simulator/linux_exec/linux_exec.v2.2.4.x86_64', '-batchmode', '-http-port=8080', '-logFile /home/jiahaoq/virtualhome-master/Player_8080.log']
Getting connection...

It got stuck when getting connection!

**Comment by xavierpuigf** [comment]
Hi! What operating system are you using? Could you check whether the executable gets to open? If you are in linux you can do:

```bash
ps -aux | grep x86_64
```

There should be a process with the executable

**Comment by CharlesQ9** [comment]
> Hi! What operating system are you using? Could you check whether the executable gets to open? If you are in linux you can do:
> 
> ```shell
> ps -aux | grep x86_64
> ```
> 
> There should be a process with the executable

Thank you! I succeeded.

**Comment by vasusharma** [comment]
Hi CharlesQ9, Could you share how you fixed this? I am running into the same issue.

**Comment by RRuschel** [comment]
Yes, same here. I checked using ps and the executable gets to open but the code just hangs on getting a connection.

**Comment by vdorbala** [comment]
Facing the same issue, can this please be reopened? I see the executable running with ps, but nothing opens up.
I'm using an Ubuntu 18.04 with version 2.2.4.
