### ISSUE TITLE
Missing some requirements

### ISSUE THREAD

**Issue by cedorman** [xavierpuigf/virtualhome#5]
When I tried to download and run, I had a couple of issues with requirements.txt

1.  No networkx, as required by display_graph.py.  Easily solvable by getting latest.

2.  Plotly did not work.  The problem appears that plotly has changed and is now under chart-studio (in version 4 and above).   So, you need to have a slightly older version (3.10).

**Comment by cedorman** [comment]
adding:
plotly==3.10
networkx==2.3
works

**Comment by xavierpuigf** [comment]
Thanks for noticing the issue. I corrected that.
