### ISSUE TITLE
X Error of failed request:  BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by sjtuytc** [xavierpuigf/virtualhome#6]
I'm trying to use docker to run simulator without monitor (headless).
When I try `docker run --mount type=bind,source="$(pwd)"/unity_vol,target=/unity_vol -p 8080:8080 -ti vh`, it says `standard_init_linux.go:211: exec user process caused "exec format error"`
When I tried run_sim.sh, it said:
`X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  83
  Current serial number in output stream:  84`
How can I solve this? thanks!

**Comment by xavierpuigf** [comment]
I just updated the docker setup, could you check up if it works on your setting? Thank you
