### ISSUE TITLE
Questions about the VirtualHome Activity Dataset

### ISSUE THREAD

**Issue by anisha2102** [xavierpuigf/virtualhome#60]
Hi @xavierpuigf,

I  am using this dataset for my research and wanted to know if there is any documentation about the contents/usage of the **VirtualHome Activity Dataset** present in http://virtual-home.org/release/programs/virtualhome_cvpr18/real.zip ?

Specifically I have trouble with the following issues:

1. I noticed that the file real_train.npz has a key called "filenames" containing _['Output_scripts_batch2/script_gen_000049'
 'Output_scripts_batch2/script_gen_000144' .. etc ]_ , but was not able to locate these files within the zip folder.
2. The paper mentions that VirtualHome Activity Dataset only contains  the 12 most frequent actions, however I found 75 unique actions under the real_train.npz file's "actions" key. 
3. If I want to use this provided dataset to initialise the environment and execute on the simulator, is there a way to get the corresponding graph states that you used for your data generation?

Thank you!

**Comment by kswain98** [comment]
Hi @anisha2102! To 75 unique actions are currently only supported for the evolving graph + VirtualHome v1.0. We are slowly adding more actions to VirtualHome so that the scripts in the dataset can be rendered in the new version.
