### ISSUE TITLE
Getting Connection Error

### ISSUE THREAD

**Issue by ltttpku** [xavierpuigf/virtualhome#62]
I tried to run Unity Simulator using Docker on my **remote server** following the instructions here: https://github.com/xavierpuigf/virtualhome/tree/master/docker, and run "./unity_vol/linux_exec.v2.2.4.x86_64  -batchmode" in the docker container.

( In another terminal:
![image](https://user-images.githubusercontent.com/88179085/156888585-844d6429-d5f4-4e29-83d0-c2191ee9c507.png)

However, when I tried running generate_video.py, I got the ERROR: 
Traceback (most recent call last):
  File "generate_video.py", line 9, in <module>
    comm.reset()
  File "../simulation/unity_simulator/comm_unity.py", line 224, in reset
    'intParams': [] if scene_index is None else [scene_index]})
  File "../simulation/unity_simulator/comm_unity.py", line 98, in post_command
    raise UnityCommunicationException(str(e))
unity_simulator.comm_unity.UnityCommunicationException: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Can you add more details on how to run Unity Simulator using Docker?
Thanks in advance :p

**Comment by kswain98** [comment]
Hi @ltttpku! Yeah we can add more detail for Docker! Thanks for pointing this out!

**Comment by ltttpku** [comment]
should add RUN chmod +x /run_sim.sh here: [https://github.com/xavierpuigf/virtualhome/blob/master/docker/Dockerfile#L129](url)

**Comment by ltttpku** [comment]
something wrong about python_version 3.6 : https://github.com/xavierpuigf/virtualhome/blob/master/docker/Dockerfile#L24
![image](https://user-images.githubusercontent.com/88179085/157208290-84e948b5-72c7-46b5-8d37-299ff7cf920a.png)

3.7.10 works for me.
