### ISSUE TITLE
the Unity exe is just a black window even the code return success

### ISSUE THREAD

**Issue by Xander23333** [xavierpuigf/virtualhome#63]
```python
>>> from simulation.unity_simulator.comm_unity import UnityCommunication
>>> comm = UnityCommunication()
>>> comm.reset(0)
True
>>> comm.add_character()
True
>>> comm.render_script(['<char0>[walk]<fridge>(1)'],find_solution = True)
(True, {'0': {'message': 'Success'}})
```

I run the simulator .exe, and the python shell show this. It seems the code works well, but my simulator just shows a black window without anything on the screen. Does I miss any parameters?

OS: Windows10

**Comment by Xander23333** [comment]
I found when I use the `comm.camera_image` the screen will display the camera image

**Comment by Xander23333** [comment]
And I cannot save the render result using the simulator. There seems be too many bugs on Windows.....

**Comment by xavierpuigf** [comment]
hi! could you try setting `recording=True` on render_script? The default is false, which is why you don't see any output. I would also recommend taking a look at the demo in this repository, for some examples on how to run render_script.

Let me know if that works!

**Comment by Xander23333** [comment]
Thanks a lot! After setting `recording=True`  I see the output.
