### ISSUE TITLE
No Output folder after running render_script ?

### ISSUE THREAD

**Issue by ltttpku** [xavierpuigf/virtualhome#65]
I can't find the Output folder after running the demo file: generate_video.py. 
```
# Generate video for a program. Make sure you have the executable open
import sys
sys.path.append('../simulation/')
from unity_simulator.comm_unity import UnityCommunication
script = ['<char0> [Walk] <tv> (1)', '<char0> [switchon] <tv> (1)'] # Add here your script
print('Starting Unity...')
comm = UnityCommunication(timeout_wait=200, docker_enabled=True)
print('Starting scene...')
comm.reset()
comm.add_character('Chars/Female1')
print('Generating video...')
res = comm.render_script(script, recording=True, find_solution=True, processing_time_limit=200,
                            output_folder='Output/')
print(res)
# print('Generated, find video in simulation/unity_simulator/output/')
```

the response in render_script():
{'id': '1646729581.108758', 'success': True, 'message': '{"0":{"message":"Success"}}', 'value': 0, 'message_list': None}
(True, {'0': {'message': 'Success'}})

OS: Ubuntu

**Comment by ltttpku** [comment]
No folder named 'Output' or 'relax' after running the following cell in unity_demo.ipynb you provided
![image](https://user-images.githubusercontent.com/88179085/157244719-f8651010-a944-4df9-9fc9-55525eb1c881.png)

![image](https://user-images.githubusercontent.com/88179085/157244968-5ca5e7a7-7496-4c82-acc1-957499e9b0fb.png)

**Comment by ge95net** [comment]
Hello, I meet the same issue, could you please help me to provide the solution of this problem? thanks a lot !
