### ISSUE TITLE
Error in using UnityEnvironment's reset function with environment_graph param

### ISSUE THREAD

**Issue by anisha2102** [xavierpuigf/virtualhome#66]
Hi,

I am trying to use the scripts from the `executable_programs` to generate my own dataset. I am not able to use the `reset` function with the parameter `environment_graph`. The execution seems to fail at `comm.expand_scene` routine.

For example, I used the following setting
i. executable program path: `programs_processed_precond_nograb_morepreconds/executable_programs/TrimmedTestScene3_graph/results_intentions_march-13-18/file425_2.txt`
ii. init_graph : `programs_processed_precond_nograb_morepreconds/init_and_final_graphs/TrimmedTestScene3_graph/results_intentions_march-13-18/file425_2.json`

If I try to reset the environment using the above init_graph, it throws an error:

Code:
```
graph = json.load(open(graph_path)) 
init_graph = graph['init_graph'] 
env.reset(environment_id=0, environment_graph=init_graph)
```

Error:
```
Message Error processing input graph: Object reference not set to an instance of an object
```

Can you please advise on how to fix this? 

Thanks a lot for sharing your work!

**Comment by kswain98** [comment]
Hi @anisha2102! Did you make sure that you are using the correct version of VirtualHome executable file with the code?

**Comment by anisha2102** [comment]
Hi @kswain98,

I have tried running it with both executables and got the same errors - 

- Latest Version 2.2.4 http://virtual-home.org/release/simulator/last_release/linux_exec.zip 
- Older version 2.0.0  https://github.com/xavierpuigf/virtualhome/releases/download/v2.0.0/linux_exec.zip 

Can you tell me which is the right executable to be used?

I keep getting errors such as:
```
Message Error processing input graph: Object reference not set to an instance of an object
```
```
Message Error processing input graph: The given key was not present in the dictionary.
```

**Comment by anisha2102** [comment]
@kswain98 
I switched to v1.0.0 and the reset function seems to be working but fails to initialize some objects. 
I also referred to the issue https://github.com/xavierpuigf/virtualhome/issues/11  - if I understand correctly these errors should not cause any issue as long as the objects that fail to initialize are not present in the script to be executed.

Closing this issue. Thanks!

**Comment by kswain98** [comment]
Hi @anisha2102! I am glad it worked out, if you encounter more issues, I suggest that you join the Discord channel since its alot easier for us to help out.

**Comment by Zoe-Ziyi** [comment]
Hi @kswain98 I switched to v1.0.0 on windows. However when render the script, I met the 408 error with 'message' of 'Timedout'. And when I use the v2.3.0 simulator, I just met the message "Object reference not set to an instance of an object". Could you please give me some suggestions? Many thanks.
