### ISSUE TITLE
Issue running Unity environment in headless AWS machine

### ISSUE THREAD

**Issue by vasusharma** [xavierpuigf/virtualhome#68]
Hi,
I am trying to run the Unity environment executable in a Linux environment on a remote headless AWS machine. 
I downloaded the executable from: http://virtual-home.org/release/simulator/last_release/linux_exec.zip
I then setup and run the X server.

Following the instructions in the Readme, I am able to execute the executable as : DISPLAY=:display_num ./{path_sim}/{exec_file}.x86_64 -batchmode

Now I want to use this inside a python script and try the other method including:
from simulation.unity_simulator import comm_unity
comm = comm_unity.UnityCommunication(file_name=file_name, port={your_port}, x_display={your_display})

However, this doesnt run for me.
This is the log it generates:
>>> from unity_simulator import comm_unity
>>> comm = comm_unity.UnityCommunication(file_name='/home/ubuntu/MARL/hctc/linux_exec.v2.2.4.x86_64', port='8000', x_display=0)
['/home/ubuntu/MARL/hctc/linux_exec.v2.2.4.x86_64', '-batchmode', '-http-port=8000', '-logFile /home/ubuntu/MARL/virtualhome/simulation/unity_simulator/Player_8000.log']
/home/ubuntu/MARL/hctc/linux_exec.v2.2.4.x86_64: error while loading shared libraries: UnityPlayer.so: cannot open shared object file: No such file or directory
Getting connection...
CLOSING PROC

It keeps waiting on Getting connection and then times out and dies. I do see a UnityPlayer.so cant be opened error, but it is present in the same folder from where I am running this so not sure why that error comes.

Any ideas?

**Comment by kswain98** [comment]
Hi @vasusharma! I will look into it tonight,  feel free to join the Discord channel: https://discord.gg/f3U92kUu4b

**Comment by xavierpuigf** [comment]
Hi @vasusharma, thanks for the note! This is an error on my side, I should include a file in the linux_exec.zip that is needed in order to run unity properly. Could you download, on the same folder where the x86_64 file is, the following file? http://virtual-home.org/release/simulator/last_release/UnityPlayer.so

We will include this in the next zip, thanks for the note!

**Comment by xavierpuigf** [comment]
You can just put the file in the same location as the x86_64 file, and you should not need to set any path variables. The unity version you are referring to should work fine, we will soon release a new version that should also be compatible though.

**Comment by IouJenLiu** [comment]
Hi 

I have the same issue here. After executing 

`comm = comm_unity.UnityCommunication(file_name="~/virtualhome/simulation/exec_linux_07_01.x86_64", port="8090", x_display="0.3")`

I got 

`Getting connection...`
`CLOSING PROC`

Thanks!

**Comment by xavierpuigf** [comment]
Hi @IouJenLiu, you seem to be using a somewhat old version of the simulator, that may not work with the params of the current API. May I know if there is any reason for using the 07_01 version? Could you also indicate which version of the API you are using?

**Comment by IouJenLiu** [comment]
Thanks so much for your prompt reply.  I switched to the latest version on master branch.  `comm_unity.UnityCommunication` works now.  Thanks so much!

Another question: When I tried to run `python test_unity_environment.py `, I got the following error: 

`['/home/iliu3/virtualhome2/simulation/linux_exec.v2.3.0.x86_64', '-batchmode', '-http-port=8081', '-logFile /home/iliu3/virtualhome2/demo/Player_8081.log']
Getting connection...
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
CLOSING PROC
`
Thanks!

**Comment by aliang8** [comment]
Also have the same issue! Bump!

**Comment by kswain98** [comment]
@IouJenLiu @aliang8 Currently only Ubuntu LTS 16/18 work, there is some issue with LTS 20. I'll get back to you with a solution if I find one.

**Comment by ishikasingh** [comment]
getting the same issue with 18 as well
`error: XDG_RUNTIME_DIR not set in the environment.`

**Comment by ishikasingh** [comment]
Works for me now, it seems I had to set the `display_num` for the X-server and the `x_display` in the code to be the same (I used display_num=2`, seems like 0 is default and gives issues sometime due to permissions).

**Comment by wang-zm18** [comment]
hello， it seems that this link is valid: http://virtual-home.org/release/simulator/last_release/UnityPlayer.so

**Comment by zzxrepository** [comment]
Hi I meet the similar problem:
my code:
`from virtualhome.simulation.unity_simulator.comm_unity import UnityCommunication

YOUR_FILE_NAME = "E:/Agent/text/progprompt-vh/virtualhome/virtualhome/simulation/unity_simulator/windows_exec/windows_exec.v2.2.4/VirtualHome.exe"
comm = UnityCommunication(file_name=YOUR_FILE_NAME)`


the problam:
Getting connection...
<Response [405]>
<Response [405]>
<Response [405]>
<Response [405]>
<Response [405]>
CLOSING PROC

After connection, it keeps returning a 405 error and then disconnects.
