### ISSUE TITLE
VirtualHome Acitivity Dataset

### ISSUE THREAD

**Issue by artyaltanzaya** [xavierpuigf/virtualhome#79]
Hello! I need to extract videos of different programs being executed on the simulation. I think potentially VirtualHome Activity Dataset is what I need, however, I cannot find from docs on how to get it. I have real.zip but there is no doc on how to run them, Can you be more specific in explaining how I can get the frames or videos of the activities being performed in the sim?

**Comment by kswain55** [comment]
Hi! This should point you to the right direction: http://virtual-home.org/documentation/master/get_started/get_started.html#generating-videos

**Comment by Zakkery0908** [comment]
Hi do you know where can i get the dataset Virtualhome activity dataset, the link on the github page is unavaliable
