### ISSUE TITLE
Cannot run simulator with sample code

### ISSUE THREAD

**Issue by Treeloveswater** [xavierpuigf/virtualhome#82]
In the Windows conda environment, I try Python to run the sample code：
**_# cd into virtualhome repo
from simulation.unity_simulator import comm_unity
YOUR_FILE_NAME = "Your path to the simulator"
comm = unity_simulator.UnityCommunication(file_name=YOUR_FILE_NAME)_**

Because there is an error prompt: NameError: name 'unity_ simulator' is not defined
so I add：
**_from simulation.unity_simulator import UnityCommunication_**

What I wrote in "Your path to the simulator" is the location of VirtualHome.exe in "windows_exec. v2.2.4"
However, there are two errors after python runs：

**_OSError: [WinError 87] 参数错误。
Exception: Error, environment was found but could not be launched_**

The complete screenshot is as follows：
![image](https://user-images.githubusercontent.com/32383826/207830780-421d168a-20aa-41bb-9ff5-8649d489eb01.png)

I can't handle these two mistakes...

**Comment by RRuschel** [comment]
I had something similar and solved it by launching my code as an administrator
