### ISSUE TITLE
The number of agents

### ISSUE THREAD

**Issue by s1eeveW** [xavierpuigf/virtualhome#87]
Hello VirtualHome team,

I read the document of VirtualHome, and there is shown 7 agents in the agent part. So, does it only have 7 agents in the VirtualHome library or it only shows 7 agents out in the document?

Thanks for providing this amazing library.

Thank you
Hanwen

**Comment by kswain55** [comment]
Hi! There are currently 7 unique agents but you can add as many as you like within a environment.
